import os
import json
from github import Github
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

gh = Github(os.getenv("GITHUB_TOKEN"))
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def generate_tests(repo_name: str, pr_number: int) -> dict:
    repo = gh.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    # Gather changed files (only code files)
    code_extensions = {'.py', '.js', '.ts', '.jsx', '.tsx', '.java', '.go', '.rs', '.cpp', '.c', '.cs'}
    changed_files = []
    for f in pr.get_files():
        ext = os.path.splitext(f.filename)[1].lower()
        if ext in code_extensions and f.patch:
            changed_files.append({
                "filename": f.filename,
                "extension": ext,
                "patch": f.patch[:4000],
                "additions": f.additions,
                "deletions": f.deletions
            })

    if not changed_files:
        return {
            "tests_generated": 0,
            "message": "No code files changed in this PR",
            "test_files": []
        }

    # Detect language
    extensions = [f["extension"] for f in changed_files]
    lang_map = {
        '.py': 'Python (pytest)',
        '.js': 'JavaScript (Jest)',
        '.ts': 'TypeScript (Jest)',
        '.jsx': 'React (Jest + React Testing Library)',
        '.tsx': 'React TypeScript (Jest + React Testing Library)',
        '.java': 'Java (JUnit 5)',
        '.go': 'Go (testing package)',
        '.rs': 'Rust (cargo test)',
    }
    detected_lang = lang_map.get(extensions[0], 'JavaScript (Jest)')

    diff_summary = "\n\n".join([
        f"File: {f['filename']}\n{f['patch']}"
        for f in changed_files[:5]
    ])

    prompt = f"""You are CognOS, an expert AI test engineer. Generate comprehensive tests for these code changes.

PR: {pr.title}
Language/Framework: {detected_lang}
Files Changed: {len(changed_files)}

Code Changes:
{diff_summary}

Generate thorough test cases covering:
1. Happy path / expected behavior
2. Edge cases
3. Error handling
4. Boundary conditions

Return a JSON object:
{{
  "language": "{detected_lang}",
  "test_strategy": "<brief explanation of testing approach>",
  "coverage_estimate_percent": <integer 0-100>,
  "test_files": [
    {{
      "filename": "<suggested test filename>",
      "description": "<what this test file covers>",
      "code": "<complete runnable test code>",
      "test_count": <number of test cases>
    }}
  ],
  "setup_instructions": "<how to run these tests>",
  "additional_recommendations": ["<rec1>", "<rec2>"]
}}

Return ONLY valid JSON. Make the test code complete and runnable."""

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
        max_tokens=3000,
    )

    raw = response.choices[0].message.content.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]

    result = json.loads(raw)

    # Post as PR comment
    test_summary = "\n".join([
        f"- `{tf['filename']}` — {tf.get('test_count', '?')} tests — {tf['description']}"
        for tf in result.get("test_files", [])
    ])

    comment = f"""## 🧪 CognOS Test Generator

**Language:** {result.get('language')}
**Estimated Coverage:** {result.get('coverage_estimate_percent')}%
**Strategy:** {result.get('test_strategy')}

### Generated Test Files
{test_summary}

### Setup
```
{result.get('setup_instructions', '')}
```

*Tests generated by CognOS AI — check the full JSON response for complete code*"""

    pr.create_issue_comment(comment)
    return result
